{application,erlach,
             [{description,"N2O VXZ Sample App"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,n2o,kvs,db,avz]},
              {mod,{web_app,[]}},
              {env,[]},
              {modules,[access,board,bpg,bpg_view,config,erlach_session,
                        erlach_view,guard,html,image,profile,root,routes,
                        thread,u,unique,web_app,web_sup]}]}.
